# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'

target 'FitnessGo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FitnessGo

  target 'FitnessGoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'FitnessGo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FitnessGo-tvOS

 # target 'FitnessGo-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

#end
